apiVersion: apps/v1
kind: Deployment
metadata:
  name: demopipeline-deployment
spec:
  selector:
    matchLabels:
      app: demopipeline
  template:
    metadata:
      labels:
        app: demopipeline
    spec:
      containers:
        - name: demopipeline
          image: devopsserdar/demopipeline:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: demopipeline-service
spec:
  selector:
    app: demopipeline
  ports:
    - port: 8083
      targetPort: 8083
  type: NodePort